# Generated by Django 4.1.5 on 2023-01-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('cc', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
            ],
        ),
    ]
