# Generated by Django 4.1.5 on 2023-01-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='myapp_empleados',
        ),
    ]
