# Generated by Django 4.1.5 on 2023-01-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_empleados_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table=None,
        ),
    ]
