# Generated by Django 4.1.5 on 2023-01-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_empleados_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='myapp_empleados',
        ),
    ]
